// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agourtxguqqjdilpzpxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnb3VydHhndXFxamRpbHB6cHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDYyNzAsImV4cCI6MjA2NjcyMjI3MH0.Eg475e4_QYeuh3j49YkCWfp3bVJPeAXtw5ozqP-Hj_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);